CostEstimate/Controllers/New/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
//using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Transactions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using CostEstimate.Models.Common;
using CostEstimate.Models.DBConnect;
using CostEstimate.Models.MyRequest;
using CostEstimate.Models.New;
using CostEstimate.Models.Table.HRMS;
using CostEstimate.Models.Table.IT;
using CostEstimate.Models.Table.LAMP;
using CostEstimate.Models.Table.MOLD;
using CostEstimate.Models.Table.MK;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.AspNetCore.Http;
using System.IO;

using MimeKit;
using MailKit.Net.Smtp;
using MailKit.Security;
using System.Net.Mail;

namespace CostEstimate.Controllers.New
{
    public class NewController : Controller
    {
        //username emppic ftpdb
        private LAMP _LAMP;
        private HRMS _HRMS;
        private IT _IT;
        private MK _MK;
        private MOLD _MOLD;
        private CacheSettingController _Cache;
        private FunctionsController _callFunc;
        public string path = @"\\thsweb\\CostEstimate\\";
        public string PgName = "CostEstimate";

        public NewController(LAMP lamp, HRMS hrms, IT it, MK mk, MOLD mold, CacheSettingController cacheController, FunctionsController callfunction)
        {
            _LAMP = lamp;
            _HRMS = hrms;
            _IT = it;
            _MK = mk;
            _MOLD = mold;
            _Cache = cacheController;
            _callFunc = callfunction;
        }

        [Authorize("Checked")]
        //public IActionResult Index(Class @class, string smLotNo, string smOrderNo, string smRevision)
        public IActionResult Index(Class @class, string smDocumentNo, string smRevision)
        {





            @class._ViewOperaterCP = new ViewOperaterCP();
            List<ViewmtMaster_Mold_Control> _ViewmtMaster_Mold_Control = _MOLD._ViewmtMaster_Mold_Control.OrderBy(x => x.mcLedger_Number).Distinct().ToList();
            SelectList formMaster_Mold_Control = new SelectList(_ViewmtMaster_Mold_Control.Select(s => s.mcLedger_Number).Distinct());
            ViewBag.vbformMaster_Mold_Control = formMaster_Mold_Control;


            List<string> _listTypeofCavity = _MK._ViewceMastType.Where(x => x.mtType.Contains("Cavity") && x.mtProgram.Contains("SubMaker")).OrderBy(x => x.mtName).Select(x => x.mtName).ToList();

            //List<string> _listTypeofCavity = new List<string>{
            //                                "CAVITIES(R/L =1 Set) x 2MOLD",
            //                                "CAVITIES(R/L =1 Set)",
            //                                "CAVITIES",
            //                                "CAVITIES x 2 MOLD",
            //                                "CAVITY x 2 MOLD",
            //                                "CAVITY"};
            SelectList _TypeofCavity = new SelectList(_listTypeofCavity);
            ViewBag.TypeofCavity = _TypeofCavity;


            // @class._ListceMastFlowApprove = _MK._ViewceMastFlowApprove.ToList();
            @class._ListceMastFlowApprove = _MK._ViewceMastFlowApprove.Where(x => x.mfFlowNo == "1").ToList();

            try
            {
                @class._ViewceMastSubMakerRequest = new ViewceMastSubMakerRequest();
                @class._listAttachment = new List<ViewAttachment>();
                // if (smLotNo != null && smOrderNo != null && smRevision != null)
                if (smDocumentNo != null)
                {
                    //@class._ViewceMastSubMakerRequest = _MK._ViewceMastSubMakerRequest.Where(x => x.smLotNo == smLotNo && x.smOrderNo == smOrderNo && x.smRevision == smRevision).FirstOrDefault();
                    @class._ViewceMastSubMakerRequest = _MK._ViewceMastSubMakerRequest.Where(x => x.smDocumentNo == smDocumentNo).FirstOrDefault();
                    //if (@class._ViewceMastSubMakerRequest == null)
                    //{
                    //    return RedirectToAction("Index", "PageNotFound");
                    //    // return View(@class);
                    //}
                    if (@class._ViewceMastSubMakerRequest == null)
                    {
                        return RedirectToAction("Index", "ErrorPage");
                        // return View(@class);
                    }

                    //@class._ListceDetailSubMakerRequest = _MK._ViewceDetailSubMakerRequest.Where(x => x.dsDocumentNo == smDocumentNo).ToList();
                    @class._ViewceMastSubMakerRequest.smTotalProCost = @class._ViewceMastSubMakerRequest.smTotalProcessWT + @class._ViewceMastSubMakerRequest.smTotalProcessCost + @class._ViewceMastSubMakerRequest.smOrderMatl + @class._ViewceMastSubMakerRequest.smTotalCost + @class._ViewceMastSubMakerRequest.smRoundUp;


                    @class._ListceDetailSubMakerRequest = new List<ViewceDetailSubMakerRequest>();
                    @class._ListceDetailSubMakerRequest = _MK._ViewceDetailSubMakerRequest.Where(x => x.dsDocumentNo == smDocumentNo).ToList();

                    if (smRevision != null)
                    {
                        @class._ViewceMastSubMakerRequest.smDocumentNo = "";
                        @class._ViewceMastSubMakerRequest.smRevision = String.Format("{0:D2}", int.Parse(@class._ViewceMastSubMakerRequest.smRevision) + 1);
                        @class._ViewceMastSubMakerRequest.smEmpCodeRequest = "";
                        @class._ViewceMastSubMakerRequest.smNameRequest = "";
                        @class._ViewceMastSubMakerRequest.smEmpCodeApprove = "";
                        @class._ViewceMastSubMakerRequest.smNameApprove = "";
                        @class._ViewceMastSubMakerRequest.smStep = 0;
                        @class._ViewceMastSubMakerRequest.smStatus = "";

                        for (int i = 0; i < @class._ListceDetailSubMakerRequest.Count(); i++)
                        {
                            @class._ListceDetailSubMakerRequest[i].dsDocumentNo = "";
                            @class._ListceDetailSubMakerRequest[i].dsRevision = String.Format("{0:D2}", int.Parse(@class._ViewceMastSubMakerRequest.smRevision) + 1);
                        }

                    }
                    else
                    {
                        @class._listAttachment = _IT.Attachment.Where(x => x.fnNo == smDocumentNo).ToList();
                    }



                    @class._ListGroupViewceDetailSubMakerRequest = @class._ListceDetailSubMakerRequest.GroupBy(p => p.dsGroupName).Select(g => new GroupViewceDetailSubMakerRequest
                    {
                        GroupName = g.Key.Trim(),
                        DetailSubMakerRequest = g.ToList()
                    }).ToList();



                }

            }
            catch (Exception ex)
            {
                ViewBag.test = ex.Message;
            }


            //ViewceMastSubMakerRequest _ViewceMastSubMakerRequest = _MK._ViewceMastSubMakerRequest.Where(x => x.smLotNo == "1").Select(""));
            //ViewceMastSubMakerRequest _ViewceMastSubMakerRequest  = _MK._ViewceMastSubMakerRequest.Where(x => x.smLotNo == "1").FirstOrDefault(); //  _MK._ViewceMastSubMakerRequest.Where(x => x.smLotNo == "1").FirstOrDefault();
            //@class._ViewceMastSubMakerRequest = _ViewceMastSubMakerRequest;

            //@class._ViewAccEMPLOYEE = _HRMS.AccEMPLOYEE.Where(x => x.EMP_CODE == id).FirstOrDefault();
            //@class._ViewceDetailSubMakerRequest.dsOrderNo = "11";
            // ViewBag.test = "11";
            return View(@class);
        }


        [Authorize("Checked")]
        //public IActionResult Index(Class @class, string smLotNo, string smOrderNo, string smRevision)
        public IActionResult Idex404(Class @class)
        {
            return View(@class);
        }

        public FileResult openFile(string pathFile)
        {
            string locationfile = path + "/" + pathFile;
            // string locationfile = @"//thsweb//MAINTENANCE_MOLD/denso_requestment.txt";
            string extension = Path.GetExtension(locationfile);
            byte[] fileByte = System.IO.File.ReadAllBytes(locationfile);

            return File(fileByte, "application/octet-stream", locationfile);

        }


        public ActionResult SearchMold_Ledger_Number(string term)
        {
            {
                List<ViewLLLedger> __ViewLLLedger = new List<ViewLLLedger>();
                __ViewLLLedger = _MOLD._ViewLLLedger.Where(p => p.LGLegNo.Contains(term)).ToList();
                // _MOLD._ViewLLLedger.Where(p => p.LGLegNo.Contains(term)).Select(p => p.LGLegNo + "" + p.LGTypeCode + "|" + p.LGCustomer + "|" + p.LGMoldName + "" + p.LGMoldNo + "|" + "0"+ "|" + p.LGIcsName).ToList());

                return Json(_MOLD._ViewLLLedger.Where(p => p.LGLegNo.Contains(term)).Select(p => p.LGLegNo + "" + p.LGTypeCode + "|" + p.LGCustomer + "|" + (p.LGMoldNo ?? "") + "/" + p.LGMoldName + "|" + "0" + "|" + (p.LGIcsName ?? "") + "|" + (p.LGPart ?? "-")).ToList());
                // return Json(_MOLD._ViewmtMaster_Mold_Control.Where(p => p.mcLedger_Number.Contains(term)).Select(p => p.mcLedger_Number + "|" + p.mcCUS + "|" + p.mcMoldname + "|" + (p.mcCavity != "" ? p.mcCavity : "0")).ToList());
            }
        }
        public ActionResult SearchModelName(string term)
        {
            {
                string a = _MK._ViewceMastCostModel.Where(p => p.mcModelName.Contains(term)).Select(p => p.mcModelName).First();
                return Json(_MK._ViewceMastCostModel.Where(p => p.mcModelName.Contains(term)).Select(p => p.mcModelName).Distinct().ToList());
            }
        }

        [HttpPost]
        public PartialViewResult SearchbyModelName(string search, Class @class)
        {
            string msg = "";
            try

CostEstimate/Views/NewMoldOtherTGR/SendMail.cshtml
@using System.Security.Claims;
@model CostEstimate.Models.Common.Class
@{
    string _UserId = User.Claims.FirstOrDefault(s => s.Type == "UserId")?.Value;
    string _NickName = User.Claims.FirstOrDefault(s => s.Type == "NICKNAME")?.Value;
    string _Name = User.Claims.FirstOrDefault(s => s.Type == "Name")?.Value;
    string _SurName = User.Claims.FirstOrDefault(s => s.Type == "SurName")?.Value;
    string _Division = User.Claims.FirstOrDefault(s => s.Type == "Division")?.Value;
    string _Section = User.Claims.FirstOrDefault(s => s.Type == "Section")?.Value;

}
@{
    Layout = null;
}
@*New Request*@
<div>

    @*@Html.HiddenFor(m => m.htEmpCode, new { id = "docno" })
        @Html.HiddenFor(m => m.htStep, new { id = "step" })
        @Html.HiddenFor(m => m.htTo, new { id = "EmailTo" })*@

    <div class="modal-header" style="margin-top:1px">
        <h5 class="modal-title">
            @*<input asp-for="htStep" type="text" class="
                     " id="txtstep" style="display:none" />
                <input asp-for="htDateIssue" type="text" class="form-control" id="txtstep" style="display:none" />*@
            <span style="font-weight: bold; font-size: 16px;">
                ส่งคำขออนุมัติเอกสาร​ --> Working Tool GR
            </span>
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="p-2-modify" style="width: 100%; border: 1px grey; padding-top: 3px;font-size:8px">

        <div class="input-group ig-property">
            <span class="input-group-text w-25" style="font-size: 13px;">From.</span>
            @*<input type="text" class="form-control" id="txtFrom"  readonly />*@
            <input type="text" class="form-control" id="txtFrom" asp-for="_ViewceHistoryApproved.htFrom" readonly style="font-size: 13px;" />
        </div>
        <div class="input-group ig-property">
            <span class="input-group-text w-25" style="font-size: 13px;">
                To
                @*@if (@Model._ViewceMastSubMakerRequest.smStep == 0)
                    {
                        <span style="padding-left:5px">DM up.</span>
                    }*@
            </span>
            <input type="text" class="form-control" id="searchInputTO" asp-for="_ViewceHistoryApproved.htTo" required style="font-size: 13px;" readonly="@(ViewBag.step == 6  ?  "readonly" : null)" />
            @*<input type="text" class="form-control" id="searchInputTO" />*@

        </div>
        <div class="input-group ig-property">
            <span class="input-group-text w-25" style="font-size: 13px;">CC.</span>
            @*<input class="form-control" id="searchInputCC" />*@
            <textarea class="form-control" id="searchInputCC" rows="4" cols="50" asp-for="_ViewceHistoryApproved.htCC" required style="font-size: 13px;"></textarea>
        </div>

        <div style="margin:5px">
            <span style=" font-size: 13px;">วันที่ : @ViewBag.vDate</span>



        </div>

        <div class="d-flex justify-content-center" style="width: 100%; text-align: center; padding-top: 5px; padding-bottom: 5px;">
            <div class="p-1-modify" style="width: 100%; border: 1px grey;   ">
                <div class="form-check form-check-inline" style="@(ViewBag.step == 4 ? "display: none;" : "")">
                    @Html.RadioButtonFor(m => m._ViewceHistoryApproved.htStatus, "Approve", new { @class = "", id = "StatusApp", onclick = "CheckDis('Approve')", required = "required", @style = "height:20px;width:20px;" }) <label style="font-size: 12px;">Approve</label><br />
                </div>
                <div class="form-check form-check-inline " style="@((ViewBag.step == 0 ) && ViewBag.step<4  ? "display: none;" : "")">
                    @Html.RadioButtonFor(m => m._ViewceHistoryApproved.htStatus, "Disapprove", new { @class = "", id = "StatusApp", onclick = "CheckDis('Disapprove')", @style = "height:20px;width:20px;" }) <label style="font-size: 12px;">Disapprove</label><br />
                </div>
            </div>
        </div>
        <div class="input-group ig-property">
            <span class="input-group-text w-25" style="font-size: 13px;">Remark</span>
            @*<input asp-for="htCC" class="form-control" id="searchInputCC" />*@
            @*<textarea class="form-control" id="Remark" rows="2" cols="50"></textarea>*@
            <textarea class="form-control" id="Remark" rows="2" cols="50" asp-for="_ViewceHistoryApproved.htRemark" style="font-size: 13px;"></textarea>
        </div>


    </div>


    <div class=" panel-group ir fadeInUp animated wowload animated" style=" animation-name: fadeInUp; margin-bottom: 5px;">
        <div class="panel panel-default property">
            <div class=" panel-heading panel-heading-custom property" tabindex="0">
                <br />
                <h4 class="panel-title faq-title-range collapsed" data-bs-toggle="collapse" data-bs-target="#History"
                    aria-expanded="false" aria-controls="collapseExample">
                    <label style="font-size:15px;font-weight:800">
                        History
                    </label>
                    <label class="lbV">
                    </label>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="History" style="overflow-y: scroll; max-height: 200px;">
                <div id="divHistory" class="panel-body">
                </div>
            </div>
        </div>
    </div>


    <div class="modal-footer" style="width: 100%;">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal" onclick="Menubar_MoldOtherTGRsavesendMailData('@Url.Action("chkSaveData", "NewMoldOtherTGR")')" style="@(@ViewBag.step == 4  ? "display:none" : "")">Send mail</button>
        @*<button type="button" class="btn btn-success" data-bs-dismiss="modal" onclick="Menubar_save_sendMailBG('@Url.Action("SaveForm_SendMail", "NewMoldModify")')" style="@(@ViewBag.step == 6  ? "display:none" : "")">Send mail</button>*@
        @*<button type="button" class="btn btn-success" data-bs-dismiss="modal" onclick="sendmailsubmit('@Url.Action("SendMail_post", "RequestForm", new { vform = @ViewBag.vForm,vSR= @ViewBag.SRno})')">Send mail</button>*@
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>



</div>



<script type="text/javascript">



$(function () {
            function split(val) {
                return val.split(/,\s*/);
            }
            function extractLast(term) {
                return split(term).pop();
            }

            $("#searchInputCC")
          // don't navigate away from the field on tab when selecting an item
          .on("keydown", function (event) {
              if (event.keyCode === $.ui.keyCode.TAB &&
                  $(this).autocomplete("instance").menu.active) {
                  event.preventDefault();
              }
          })
            .autocomplete({
                minLength: 0,
                source: function (request, response) {
                    $.getJSON('@Url.Action("Search", "New")', {
                        term: extractLast(request.term)
                    }, response);
                },
                focus: function () {
                    // prevent value inserted on focus
                    return false;
                },
                select: function (event, ui) {
                    const email365 = ui.item.value.split("|")[1];
                    //let email365 = myArray[0];
                    console.log("test" + email365);

                    var terms = split(this.value);
                    // remove the current input
                    terms.pop();
                    // add the selected item

                    //terms.push(ui.item.value);
                    terms.push(email365);
                    // add placeholder to get the comma-and-space at the end
                    terms.push("");
                    this.value = terms.join(",");
                    return false;
                }
                });


            $("#searchInputCCDept")
          // don't navigate away from the field on tab when selecting an item
          .on("keydown", function (event) {
              if (event.keyCode === $.ui.keyCode.TAB &&
                  $(this).autocomplete("instance").menu.active) {
                  event.preventDefault();
              }
          })
            .autocomplete({
                minLength: 0,
                source: function (request, response) {
                    $.getJSON('@Url.Action("Search", "New")', {
                        term: extractLast(request.term)
                    }, response);
                },
                focus: function () {
                    // prevent value inserted on focus
                    return false;
                },
                select: function (event, ui) {
                    const email365 = ui.item.value.split("|")[1];
                    //let email365 = myArray[0];
                    console.log("test" + email365);

                    var terms = split(this.value);
                    // remove the current input
                    terms.pop();
                    // add the selected item

                    //terms.push(ui.item.value);
                    terms.push(email365);
                    // add placeholder to get the comma-and-space at the end
                    terms.push("");
                    this.value = terms.join(",");
                    return false;
                }
            });

             $("#searchInputTO")
          // don't navigate away from the field on tab when selecting an item
                 .on("keydown", function (event) {
                     console.log("OK");
              if (event.keyCode === $.ui.keyCode.TAB &&
                  $(this).autocomplete("instance").menu.active) {
                  event.preventDefault();
              }
          })
            .autocomplete({
                minLength: 1,
                source: function (request, response) {
                    $.getJSON('@Url.Action("Search", "New")', {
                        term: extractLast(request.term)
                    }, response);
                },
                focus: function () {
                    // prevent value inserted on focus
                    return false;
                },
                select: function (event, ui) {
                    const email365 = ui.item.value.split("|")[1];
                    //let email365 = myArray[0];
                    console.log("test" + email365);

                    var terms = split(this.value);
                    // remove the current input
                    terms.pop();
                    // add the selected item

                    //terms.push(ui.item.value);
                    terms.push(email365);
                    // add placeholder to get the comma-and-space at the end
                    terms.push("");
                    this.value = terms.join("");
                    return false;
                }
            });
    })

</script>

CostEstimate/Views/NewMoldOtherTGR/_PartialStepFlowOtherRequest.cshtml
@model CostEstimate.Models.Common.Class;
<div class="card-body" id="FormFlow" style="background-color: unset;padding-top:10px;">
    <div class="grid-item fw-800 center " style="text-align:left;font-size:15px">Approve and Check step </div>

    <br />
    @*<div style="display: flex; justify-content: center;">*@
    <div style="width: 100%;">
        <ul class="progressbar ">
            @if (@Model._ListceMastFlowApprove != null && @Model._ViewceMastToolGRRequest != null)
            {
                @for (int i = 0; i < Model._ListceMastFlowApprove.Count - 2; i++)
                {
                    <li class="@(@Model._ViewceMastToolGRRequest.trStep >= i ? "active" : "")">
                        <span style="@(i==@Model._ViewceMastToolGRRequest.trStep ? "font-size:12.5px;color:#78a820;font-weight: 600":"font-size:11px;color:black;")" class="step-title">@Model._ListceMastFlowApprove[i].mfSubject</span>

                        @*<span style="@(@Model._ViewceMastSubMakerRequest.smStep == 7 && i==7 ? "font-size:11px;color:green;font-weight: 600":"font-size:10px;color:black;")" class="step-title">@Model._ListceMastFlowApprove[i].mfSubject</span>*@

                        @*<span style="font-size:10px;color:black" class="step-title">@Model._ListceMastFlowApprove[i].mfSubject</span>*@
                    </li>
                }
            }
        </ul>
    </div>


    @*<hr />*@
</div>

<style>

    .container {
        width: 100%;
        margin: auto;
    }

    .text-msg {
        margin: 20px 0;
        display: block;
        clear: both;
        text-align: justify;
    }

    /*.progressbar {
       
        display: flex;
        padding: 0;
        margin: 0;
        list-style: none;
        counter-reset: step;
        width: auto;
        padding-left: 10%;
    }*/
    .progressbar {
        display: flex;
        padding: 0;
        margin: 0;
        list-style: none;
        counter-reset: step;
        width: 100%;
        justify-content: space-between; /* กระจาย item เต็มพื้นที่ */



    }


        .progressbar li {
            flex: 1;
            min-width: 100px; /* ป้องกันเล็กเกิน */
          
            text-align: center;
            list-style-type: none;
            width: 10%;
            /*width: 11%;*/
            float: left;
            font-size: 15px;
            margin-top: 25px;
            padding-top: 5px;
            position: relative;
            text-align: center;
            /*text-transform: uppercase;*/
            color: #7d7d7d;
            z-index: 5;
            margin: 9px;
        }

            .progressbar li:before {
                width: 38px;
                height: 38px;
                content: counter(step);
                counter-increment: step;
                line-height: 30px;
                border: 2px solid #7d7d7d;
                display: block;
                text-align: center;
                margin: 0 auto 10px auto;
                border-radius: 50%;
                background-color: white;
            }

            .progressbar li:after {
                width: 100%;
                height: 2px;
                content: '';
                position: absolute;
                background-color: #7d7d7d;
                border: 1.5px solid;
                top: 24px;
                left: -50%;
                z-index: -1;
            }

            .progressbar li:first-child:after {
                content: none;
            }

            .progressbar li.active {
                color: #9bbd5e; /*#0dcaf0;*/
            }

                .progressbar li.active:before {
                    border-color: #9bbd5e; /*#0dcaf0;*/
                }

                .progressbar li.active + li:after {
                    background-color: #9bbd5e; /*#0dcaf0;*/
                }
</style>

CostEstimate/Views/NewMoldOtherTGR/_PartialTGRAttachFile.cshtml
@model CostEstimate.Models.Common.Class;
@{
    //string _Permission = User.Claims.FirstOrDefault(s => s.Type == "Permission").Value;
    string _UserId = User.Claims.FirstOrDefault(s => s.Type == "UserId")?.Value;
    string _NickName = User.Claims.FirstOrDefault(s => s.Type == "NICKNAME")?.Value;
    string _Name = User.Claims.FirstOrDefault(s => s.Type == "Name")?.Value;
    string _SurName = User.Claims.FirstOrDefault(s => s.Type == "SurName")?.Value;
    string _Division = User.Claims.FirstOrDefault(s => s.Type == "Division")?.Value;
    string _Section = User.Claims.FirstOrDefault(s => s.Type == "Section")?.Value;

}
<link href="~/css/Home/siteHome.css" rel="stylesheet" />
@*Attach file*@
<div class="row center">
    <div class="col-5 " style="">

    </div>
    <div class="col-90 " style="border:0.5px solid gray;padding:10px">
        <div class="row center">
            <div class="col-20 " style="">
                <div class="grid-item fw-800 center" style="text-align:left;text-decoration: underline;font-size:13px">Attach file</div>
            </div>
            <div class="col-80 " style="text-align:left">
                <input name="files" type="file" id="files" multiple="" class="button btnGray " style="width:300px">
                @*<button type="button" class="button notification" style="width:auto; height:28px;background-color:#7286D3" data-bs-toggle="modal" id="btnfileMoldOtherTGR">
                    <img src="~/images/open-folder.png" style="width:25px;height:25px;margin-left:0px;text-align:left">
               
                    เปิดไฟล์แนบ @Model._listAttachment.Count() ไฟล์
                    @if (@Model._listAttachment.Count() > 0)
                    {
                        <span class="badge">@Model._listAttachment.Count()</span>
                    }
                 
                </button>*@
                <button type="button" class="button notification"
                        style="width:auto; height:28px;background-color:#7286D3"
                        data-bs-toggle="modal"
                        data-bs-target="#myModalNewMoldOtherTGR"
                        id="btnfileMoldOtherTGR">
                    <img src="~/images/open-folder.png" style="width:25px;height:25px;margin-left:0px;text-align:left">
                    เปิดไฟล์แนบ @Model._listAttachment.Count() ไฟล์
                    @if (@Model._listAttachment.Count() > 0)
                    {
                        <span class="badge">@Model._listAttachment.Count()</span>
                    }
                </button>

            </div>
        </div>

    </div>
    <div class="col-5 " style="">

    </div>
</div>